[package]
name = "nvenc-sys"
version = "0.1.0"
authors = ["Qiu Wenbo <crab2313@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
bindgen = "0.49.0"
